# Generated by Django 5.1.2 on 2024-10-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLUB', 'Club'), ('EVENTORGANIZER', 'Eventorganizer')], max_length=50),
        ),
    ]
