# Generated by Django 5.1.2 on 2024-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLUB', 'Club'), ('EVENTORGANIZER', 'Eventorganizer'), ('SCHOOL', 'School'), ('COLLEGE', 'College')], max_length=50),
        ),
    ]
